# Dependencies
#markdown:         redcarpet
markdown: kramdown
pygments:         true
gems:
  - jekyll-paginate-v2

# Permalinks
permalink:        pretty

# Setup
title:            Yu's Tech 블로그
tagline:          프로그래밍 이야기
description:      'You will never know until you try.'
url:              http://yujaeseo.github.io
search: true
author:
  name:           'Jaeseo Yu'

collections :
  category:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type : category
    values:
      layout: "category"
    
paginate: 2
paginate_path: "/page:num/"
# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Yujaeseo/Yujaeseo.github.io.git
  
