# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yu's Tech 블로그
tagline:          프로그래밍 이야기
description:      You will never know until you try.'
url:              http://yujaeseo.github.io
search: true

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Yujaeseo/Yujaeseo.github.io.git
